### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Zorgcz** [JaraLowell/LoraLog#3]
There is typo in line nr.905 when you create db.

                cursor.execute("INSERT INTO node_info (node_id, hex_id, short_name, long_name, timefirst) VALUES (?, ?, ?, ?. ?)", (info["num"], nodeID,nodeID[-4:],'Meshtastic ' + nodeID[-4:], tnow))

**Comment by JaraLowell** [comment]
Am i blind or don't i see it ?

**Comment by Zorgcz** [comment]
Sorry, it is a dot in place of a comma.   VALUES (?, ?, ?, ?**.** ?)

**Comment by JaraLowell** [comment]
Yep found it, great catch :) i'l send comit with fix
